openapi: 3.0.3
info:
  title: Device API
  description: API endpoints for managing devices
  version: 1.0.0

servers:
  - url: http://localhost:3000/unihome/api
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /listDevices:
    get:
      summary: Retrieve all devices
      responses:
        '200':
          description: A list of devices
      security:
        - bearerAuth: []

  /listDevice/{ID}:
    get:
      summary: Retrieve a single device by ID
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
          description: ID of the device to retrieve
      responses:
        '200':
          description: A single device object
        '404':
          description: Device not found
      security:
        - bearerAuth: []

  /createDevice:
    post:
      summary: Create a new device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessCode:
                  type: number
                  description: Access code for use the device
                RoomID:
                  type: number
                  minimum: 1
                  description: ID of the room associated with the device
                DeviceTypeID:
                  type: number
                  minimum: 1
                  description: ID of the device type
      responses:
        '201':
          description: Device created successfully
        '400':
          description: Invalid request
      security:
        - bearerAuth: []

  /updateDevice/{ID}:
    put:
      summary: Update a device by ID
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
          description: ID of the device to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessCode:
                  type: number
                  description: Access code for use the device
      responses:
        '200':
          description: Device updated successfully
        '400':
          description: Invalid request
        '404':
          description: Device not found
      security:
        - bearerAuth: []

  /deleteDevice/{ID}:
    delete:
      summary: Delete a device by ID
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
          description: ID of the device to delete
      responses:
        '204':
          description: Device deleted successfully
        '404':
          description: Device not found
      security:
        - bearerAuth: []